-- Dev seed: Create payroll accumulation and payroll run for current month
BEGIN;

DO $$
DECLARE
  v_admin_id UUID;
  v_admin2_id UUID;
  v_default_company_id UUID;
  v_company2_id UUID;
  v_emp RECORD;
  v_current_month DATE;
  v_current_year INT;
  v_run_id UUID;
BEGIN
  SELECT id INTO v_admin_id FROM users WHERE username = 'admin' AND deleted_at IS NULL LIMIT 1;
  SELECT id INTO v_admin2_id FROM users WHERE username = 'admin2' AND deleted_at IS NULL LIMIT 1;
  SELECT id INTO v_default_company_id FROM companies WHERE code = 'DEFAULT' LIMIT 1;
  SELECT id INTO v_company2_id FROM companies WHERE code = 'COMPANY2' LIMIT 1;
  
  v_current_month := date_trunc('month', CURRENT_DATE)::date;
  v_current_year := EXTRACT(YEAR FROM CURRENT_DATE)::INT;

  -- =====================================================
  -- PAYROLL ACCUMULATION - YTD data per employee
  -- =====================================================
  FOR v_emp IN 
    SELECT e.id, e.employee_number, e.company_id, e.base_pay_amount,
           e.sso_contribute, e.provident_fund_contribute
    FROM employees e
    JOIN employee_type t ON t.id = e.employee_type_id
    WHERE t.code = 'full_time' AND e.deleted_at IS NULL
  LOOP
    -- SSO accumulation (yearly)
    IF v_emp.sso_contribute THEN
      INSERT INTO payroll_accumulation (
        employee_id, company_id, accum_type, accum_year, amount, updated_by
      ) VALUES (
        v_emp.id, v_emp.company_id, 'sso', v_current_year,
        CASE 
          WHEN position('001' in v_emp.employee_number) > 0 THEN 8250.00
          WHEN position('002' in v_emp.employee_number) > 0 THEN 7700.00
          ELSE 6600.00
        END,
        v_admin_id
      ) ON CONFLICT DO NOTHING;
      
      -- SSO employer
      INSERT INTO payroll_accumulation (
        employee_id, company_id, accum_type, accum_year, amount, updated_by
      ) VALUES (
        v_emp.id, v_emp.company_id, 'sso_employer', v_current_year,
        CASE 
          WHEN position('001' in v_emp.employee_number) > 0 THEN 8250.00
          WHEN position('002' in v_emp.employee_number) > 0 THEN 7700.00
          ELSE 6600.00
        END,
        v_admin_id
      ) ON CONFLICT DO NOTHING;
    END IF;
    
    -- Income accumulation (yearly)
    INSERT INTO payroll_accumulation (
      employee_id, company_id, accum_type, accum_year, amount, updated_by
    ) VALUES (
      v_emp.id, v_emp.company_id, 'income', v_current_year,
      v_emp.base_pay_amount * 11, -- 11 months of salary
      v_admin_id
    ) ON CONFLICT DO NOTHING;
    
    -- PF accumulation (lifetime - no year)
    IF v_emp.provident_fund_contribute THEN
      INSERT INTO payroll_accumulation (
        employee_id, company_id, accum_type, accum_year, amount, updated_by
      ) VALUES (
        v_emp.id, v_emp.company_id, 'pf', NULL,
        CASE 
          WHEN position('001' in v_emp.employee_number) > 0 THEN 17600.00
          WHEN position('002' in v_emp.employee_number) > 0 THEN 9240.00
          ELSE 5500.00
        END,
        v_admin_id
      ) ON CONFLICT DO NOTHING;
      
      INSERT INTO payroll_accumulation (
        employee_id, company_id, accum_type, accum_year, amount, updated_by
      ) VALUES (
        v_emp.id, v_emp.company_id, 'pf_employer', NULL,
        CASE 
          WHEN position('001' in v_emp.employee_number) > 0 THEN 17600.00
          WHEN position('002' in v_emp.employee_number) > 0 THEN 9240.00
          ELSE 5500.00
        END,
        v_admin_id
      ) ON CONFLICT DO NOTHING;
    END IF;
  END LOOP;
  
  RAISE NOTICE 'Created payroll accumulation records';

  -- =====================================================
  -- PAYROLL RUN - create for ALL branches (pending)
  -- Note: payroll_run_item is auto-generated by trigger
  -- =====================================================
  
  FOR v_emp IN (
    SELECT b.id, b.company_id 
    FROM branches b
    JOIN companies c ON c.id = b.company_id
    WHERE b.deleted_at IS NULL AND c.code IN ('DEFAULT', 'COMPANY2')
  ) LOOP
    IF NOT EXISTS (
      SELECT 1 FROM payroll_run 
      WHERE branch_id = v_emp.id AND payroll_month_date = v_current_month AND deleted_at IS NULL
    ) THEN
      INSERT INTO payroll_run (
        company_id, branch_id,
        payroll_month_date, period_start_date, pay_date,
        social_security_rate_employee, social_security_rate_employer,
        status, created_by, updated_by
      ) VALUES (
        v_emp.company_id, v_emp.id,
        v_current_month, v_current_month,
        (v_current_month + interval '1 month' - interval '1 day')::date,
        0.05, -- 5%
        0.05,
        'pending',
        CASE WHEN v_emp.company_id = v_default_company_id THEN v_admin_id ELSE v_admin2_id END,
        CASE WHEN v_emp.company_id = v_default_company_id THEN v_admin_id ELSE v_admin2_id END
      );
      RAISE NOTICE 'Created pending payroll run for branch: %', v_emp.id;
    ELSE
      RAISE NOTICE 'Pending payroll run already exists for branch: %', v_emp.id;
    END IF;
  END LOOP;

END $$;

COMMIT;
