// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/activity-logs": {
            "get": {
                "responses": {}
            }
        },
        "/admin/activity-logs/filter-options": {
            "get": {
                "responses": {}
            }
        },
        "/admin/branches": {
            "get": {
                "responses": {}
            },
            "post": {
                "responses": {}
            }
        },
        "/admin/branches/{id}": {
            "get": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            },
            "patch": {
                "responses": {}
            }
        },
        "/admin/branches/{id}/default": {
            "put": {
                "responses": {}
            }
        },
        "/admin/branches/{id}/employee-count": {
            "get": {
                "responses": {}
            }
        },
        "/admin/branches/{id}/status": {
            "patch": {
                "responses": {}
            }
        },
        "/admin/company/current": {
            "get": {
                "responses": {}
            },
            "put": {
                "responses": {}
            }
        },
        "/admin/payroll-configs": {
            "get": {
                "responses": {}
            },
            "post": {
                "responses": {}
            }
        },
        "/admin/payroll-configs/effective": {
            "get": {
                "responses": {}
            }
        },
        "/admin/payroll-org-logos": {
            "post": {
                "responses": {}
            }
        },
        "/admin/payroll-org-logos/{id}": {
            "get": {
                "responses": {}
            }
        },
        "/admin/payroll-org-logos/{id}/meta": {
            "get": {
                "responses": {}
            }
        },
        "/admin/payroll-org-profiles": {
            "get": {
                "responses": {}
            },
            "post": {
                "responses": {}
            }
        },
        "/admin/payroll-org-profiles/effective": {
            "get": {
                "responses": {}
            }
        },
        "/admin/payroll-org-profiles/{id}": {
            "get": {
                "responses": {}
            }
        },
        "/admin/users": {
            "get": {
                "responses": {}
            },
            "post": {
                "responses": {}
            }
        },
        "/admin/users/{id}": {
            "get": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            },
            "patch": {
                "responses": {}
            }
        },
        "/admin/users/{id}/password-reset": {
            "post": {
                "responses": {}
            }
        },
        "/admin/users/{userId}/branches": {
            "get": {
                "responses": {}
            },
            "put": {
                "responses": {}
            }
        },
        "/auth/login": {
            "post": {
                "responses": {}
            }
        },
        "/auth/logout": {
            "post": {
                "responses": {}
            }
        },
        "/auth/refresh": {
            "post": {
                "responses": {}
            }
        },
        "/auth/switch": {
            "post": {
                "responses": {}
            }
        },
        "/bonus-cycles": {
            "get": {
                "responses": {}
            },
            "post": {
                "responses": {}
            }
        },
        "/bonus-cycles/{id}": {
            "get": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            },
            "patch": {
                "responses": {}
            }
        },
        "/bonus-cycles/{id}/items": {
            "get": {
                "responses": {}
            }
        },
        "/bonus-items/{id}": {
            "patch": {
                "responses": {}
            }
        },
        "/dashboard/attendance-summary": {
            "get": {
                "responses": {}
            }
        },
        "/dashboard/attendance-top-employees": {
            "get": {
                "responses": {}
            }
        },
        "/dashboard/employee-summary": {
            "get": {
                "responses": {}
            }
        },
        "/dashboard/financial-summary": {
            "get": {
                "responses": {}
            }
        },
        "/dashboard/payroll-summary": {
            "get": {
                "responses": {}
            }
        },
        "/debt-txns": {
            "get": {
                "responses": {}
            }
        },
        "/debt-txns/create-plan": {
            "post": {
                "responses": {}
            }
        },
        "/debt-txns/repayment": {
            "post": {
                "responses": {}
            }
        },
        "/debt-txns/{employeeId}/outstanding-installments": {
            "get": {
                "responses": {}
            }
        },
        "/debt-txns/{id}": {
            "get": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            }
        },
        "/debt-txns/{id}/approve": {
            "post": {
                "responses": {}
            }
        },
        "/documents/expiring": {
            "get": {
                "responses": {}
            }
        },
        "/employee-document-types": {
            "get": {
                "responses": {}
            },
            "post": {
                "responses": {}
            }
        },
        "/employee-document-types/{id}": {
            "put": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            }
        },
        "/employees": {
            "get": {
                "responses": {}
            },
            "post": {
                "responses": {}
            }
        },
        "/employees/accumulations/{accumId}": {
            "delete": {
                "responses": {}
            }
        },
        "/employees/photos": {
            "post": {
                "responses": {}
            }
        },
        "/employees/photos/{id}": {
            "get": {
                "responses": {}
            }
        },
        "/employees/{id}": {
            "get": {
                "responses": {}
            },
            "put": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            }
        },
        "/employees/{id}/accumulations": {
            "get": {
                "responses": {}
            },
            "post": {
                "responses": {}
            }
        },
        "/employees/{id}/documents": {
            "get": {
                "responses": {}
            },
            "post": {
                "responses": {}
            }
        },
        "/employees/{id}/documents/{docId}": {
            "put": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            }
        },
        "/employees/{id}/documents/{docId}/file": {
            "get": {
                "responses": {}
            }
        },
        "/employees/{id}/photo": {
            "delete": {
                "responses": {}
            }
        },
        "/master/departments": {
            "post": {
                "responses": {}
            }
        },
        "/master/departments/{id}": {
            "delete": {
                "responses": {}
            },
            "patch": {
                "responses": {}
            }
        },
        "/master/employee-positions": {
            "post": {
                "responses": {}
            }
        },
        "/master/employee-positions/{id}": {
            "delete": {
                "responses": {}
            },
            "patch": {
                "responses": {}
            }
        },
        "/me": {
            "get": {
                "responses": {}
            }
        },
        "/me/companies": {
            "get": {
                "responses": {}
            }
        },
        "/me/password": {
            "put": {
                "responses": {}
            }
        },
        "/payouts/pt": {
            "get": {
                "responses": {}
            },
            "post": {
                "responses": {}
            }
        },
        "/payouts/pt/{id}": {
            "get": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            }
        },
        "/payouts/pt/{id}/pay": {
            "post": {
                "responses": {}
            }
        },
        "/payroll-items/{id}": {
            "get": {
                "responses": {}
            },
            "patch": {
                "responses": {}
            }
        },
        "/payroll-runs": {
            "get": {
                "responses": {}
            },
            "post": {
                "responses": {}
            }
        },
        "/payroll-runs/{id}": {
            "get": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            },
            "patch": {
                "responses": {}
            }
        },
        "/payroll-runs/{id}/items": {
            "get": {
                "responses": {}
            }
        },
        "/public/branding": {
            "get": {
                "responses": {}
            }
        },
        "/public/branding/logo": {
            "get": {
                "responses": {}
            }
        },
        "/salary-advances": {
            "get": {
                "responses": {}
            },
            "post": {
                "responses": {}
            }
        },
        "/salary-advances/{id}": {
            "get": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            },
            "patch": {
                "responses": {}
            }
        },
        "/salary-raise-cycles": {
            "get": {
                "responses": {}
            },
            "post": {
                "responses": {}
            }
        },
        "/salary-raise-cycles/{id}": {
            "get": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            },
            "patch": {
                "responses": {}
            }
        },
        "/salary-raise-cycles/{id}/items": {
            "get": {
                "responses": {}
            }
        },
        "/salary-raise-items/{id}": {
            "patch": {
                "responses": {}
            }
        },
        "/super-admin/activity-logs": {
            "get": {
                "responses": {}
            }
        },
        "/super-admin/activity-logs/filter-options": {
            "get": {
                "responses": {}
            }
        },
        "/super-admin/companies": {
            "get": {
                "responses": {}
            },
            "post": {
                "responses": {}
            }
        },
        "/super-admin/companies/{id}": {
            "get": {
                "responses": {}
            },
            "patch": {
                "responses": {}
            }
        },
        "/super-admin/employee-document-types": {
            "get": {
                "responses": {}
            },
            "post": {
                "responses": {}
            }
        },
        "/super-admin/employee-document-types/{id}": {
            "put": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            }
        },
        "/worklogs/ft": {
            "get": {
                "responses": {}
            },
            "post": {
                "responses": {}
            }
        },
        "/worklogs/ft/{id}": {
            "get": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            },
            "patch": {
                "responses": {}
            }
        },
        "/worklogs/pt": {
            "get": {
                "responses": {}
            },
            "post": {
                "responses": {}
            }
        },
        "/worklogs/pt/{id}": {
            "get": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            },
            "patch": {
                "responses": {}
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Add \"Bearer \u003caccess token\u003e\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "HR Payroll API",
	Description:      "HR Payroll REST API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
